# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master

      # Runs a single command using the runners shell
      - name: Login to Azure
        uses: azure/login@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS_GITHUB_SECRET }}

      - name: Setup ssh for VM
        run: az vm user update -u sshUser --ssh-key-value "${{ secrets.SSH_KEY }}" -n tellmewhy -g ninadkavimandan
      
      - name: Open port 80 on VM
        run: az vm open-port --port 80 --resource-group ninadkavimandan --name tellmewhy
      
      - name: Setup IIS on windows VM
        run: az vm run-command invoke --command-id RunPowerShellScript --name tellmewhy -g ninadkavimandan --scripts 'Install-WindowsFeature -name Web-Server -IncludeManagementTools'
      
      - name: Copy index.html to IIS root
        run: scp ./index.html sshUser@104.215.83.167:/NewDirectory/index.html && az vm run-command invoke --command-id RunPowerShellScript --name tellmewhy -g ninadkavimandan --scripts 'move NewDirectory/index.html C:/Inetpub/wwwroot/index.html'
      
      - name: Logout from Azure
        run: |
          az logout
